CREATE TABLE ktservice_video (
  id CHAR(32) PRIMARY KEY,
  created TIMESTAMP NOT NULL,
  modified TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NULL,
  syncState VARCHAR(255) NOT NULL
);
